export const SERVICE_LIST = {
  USER_SERVICE: 'USER_SERVICE',
  PROJECT_SERVICE: 'PROJECT_SERVICE',
  TWEETS_SERVICE: 'TWEETS_SERVICE',
  TASK_SERVICE: 'TASK_SERVICE',
  COMMENT_SERVICE: 'COMMENT_SERVICE',
};
